-- Table: public.fct_attack_summary
-- This fact table is designed to only include relevant columns 
-- from the ids_traffic staging table. This is done to reduce 
-- data model space and improve refresh speeds. The data types 
-- have been updated for proper mappings and a summary of benign 
-- and attack flows are included. The fact table includes a 
-- replica of data and updated to 2017 along with few data 
-- manipulations and changes done to show a previous period 
-- comparison in Power BI dashboard.

-- DROP TABLE IF EXISTS public.fct_attack_summary;

CREATE TABLE IF NOT EXISTS public.fct_attack_summary
(
    report_date date,
    report_hour numeric,
    protocol integer,
    "Port_ID" bigint,
    "NIST_Id" bigint,
    fct_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    src_ip inet,
    dst_ip inet,
    CONSTRAINT fct_attack_summary_pkey PRIMARY KEY (fct_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.fct_attack_summary
    OWNER to postgres;